logging:
  backup_count: 3
  level: INFO
  max_size_mb: 10
models:
  default: gpt-3.5-turbo
  last_used: gpt-4
paths:
  log_file: ./logs/automation.log
  transcript_folder: /Users/thomasvogt/Downloads/TRS
webui:
  api_key: ${OPENWEBUI_API_KEY}  # API key will be loaded from environment variable
  url: https://your-openwebui-server.com  # Replace with your OpenWebUI server URL
